version: "3.9"

services: 
  fullstack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullstack-app
    ports:
      - "8080:8080" # access Spring Boot on localhost:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - h2_data:/data # persist H2 files
    restart: unless-stopped

volumes:
  h2_data:
    driver: local
